# Generated by Django 5.2.4 on 2025-07-21 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookDemo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullName", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("companyName", models.CharField(max_length=100)),
                ("jobTitle", models.CharField(max_length=100)),
                ("industry", models.CharField(max_length=50)),
                ("members", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="PhoneNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("countryCode", models.CharField(max_length=10)),
                ("number", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullName", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("projectName", models.CharField(max_length=100)),
                ("services", models.CharField(max_length=100)),
                ("message", models.TextField()),
                (
                    "phone",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dataapi.phonenumber",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Career",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullName", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("linkedIn", models.URLField()),
                ("currentLocation", models.CharField(max_length=100)),
                ("job", models.CharField(max_length=100)),
                ("jobType", models.CharField(max_length=50)),
                (
                    "phone",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dataapi.phonenumber",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "bookDemo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dataapi.bookdemo",
                    ),
                ),
                (
                    "career",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="dataapi.career"
                    ),
                ),
                (
                    "contact",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dataapi.contact",
                    ),
                ),
            ],
        ),
    ]
